# Generated by Django 4.2.6 on 2023-10-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='photo', verbose_name='My Photo'),
            preserve_default=False,
        ),
    ]
